{% set name = "spatialgeometry" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spatialgeometry-{{ version }}.tar.gz
  sha256: 98b2b1023eed6197d26f31cf4643c51d1a41059ac6036a10b16dc389ec6af5a6

build:
  number: 3
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - numpy
    - pip
    - setuptools
    - python
  run:
    - python
    - spatialmath-python >=1.0.0
    - numpy

test:
  imports:
    - spatialgeometry
    - spatialgeometry.tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jhavl/spatialgeometry
  summary: A Shape and Geometry Package
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
