{% set name = "spatialgeometry" %}
{% set version = "1.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/spatialgeometry-{{ version }}.tar.gz
  sha256: a38dc8350ccff166214533073f8836fc6cf4c111aec919bc404fb28609ac0ff1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - numpy
    - pip
    - setuptools
    - scikit-build-core
    - python
    - nanobind
  run:
    - python
    - spatialmath-python >=1.0.0
    - numpy

test:
  imports:
    - spatialgeometry
    - spatialgeometry.tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jhavl/spatialgeometry
  summary: A Shape and Geometry Package
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
